### ISSUE TITLE
Camera goes underground and far from the player in worldspace

### ISSUE THREAD

**Issue by Hunk92** [mwilsnd/SkyrimSE-SmoothCam#37] opened 2020-12-09 20:25 UTC
hello, i have a really strange bug.

Everything was working fine until my 3rd person camera pov suddently goes all wrong.

- This bug only happen in worldspace, in interior everything is fine.
- Mounting a horse don't reset the bug but the camera on horse works without any issue.
- Revert to 1.1 make the 3rd person camera in worldspace working again but the bug is still there if I re-install 1.3 after a save from 1.1
- Doing a clean save don't solve the issue If i re-install 1.3

When the bug happen, I think Smoothcam 1.3 change a parameter that the savegame keep so disable/clean save/enable the mod don't change anything.

**Comment by Hunk92** [comment] 2020-12-09 20:30
https://image.noelshack.com/fichiers/2020/50/3/1607545811-enb2020-12-9-21-26-30.jpg

https://image.noelshack.com/fichiers/2020/50/3/1607545808-enb2020-12-9-21-27-45.jpg

**Comment by mwilsnd** [comment] 2021-08-03 17:44
While I was never able to pin down exactly why this would happen, you can try the 1.4 version and see if things improve - I have tried to address this purely based on some assumptions so I'm interested in seeing if it works.

**Comment by Hunk92** [comment] 2021-08-05 21:40
Hello,

I tried your new version 1.4.2. Sadly, the bug is still there on my older save. I've found the issue and replied on the bug section of the nexus some time ago.

Apparently, it's related to the mod Vilja in skyrim. This mod spawn an inivisible pnj in front of my character and smoothcam hook on his feet (or its skeleton first node). After I disable the pnj, smoothcam work normally.

I discovered that with the minimap mod.

**Comment by floydfire** [comment] 2021-08-17 21:23
If it can be of any help it happens when you dance with Vilja (in a tavern or at the wedding) i think, don't know if it happens also for other things, but the hugs doesn't cause the issue. I think it can also be when she hugs you in an interior maybe? Also enabling the "walking side by side" function of vilja trigger the issue. (you can find it in Travelling Together-> regarding your following behavior-> walk side by side) 

EDIT: I think you can ignore everything i said, i managed to trigger it everytime by activating Travelling Together -> Regarding You Following Behavoir -> You can look around when we are not moving -> you may run ahead if you wish. It also do the same if you do Travelling Together -> Regarding you following behavoir -> You may run ahead if you wish  Deactivating that option from vilja doesn't fix the issue though. IF you don't select "you may run ahead if you wish" after "you can look around when we are not moving" and just exit the conversation you don't get the camera falling into the earth, so i think one thing that cause for certain the issue is the option "you may run ahead if you wish"

**Comment by mwilsnd** [comment] 2021-08-17 22:54
Interesting, thanks for the info on how to trigger it. I'll install the mod and figure out what is going on.

**Comment by floydfire** [comment] 2021-08-17 22:58
I'll continue to edit my comment instead of posting new comments if i find something more so i will not clutter too much this issue

**Comment by mwilsnd** [comment] 2021-08-30 08:15
Alright I was able to track this down and figure out what is going on, it'll be fixed in the next version.

**Comment by floydfire** [comment] 2021-09-04 12:12
I don't know if it's the same issue but i found out that a similar issue happens with wyrmstooth in the part of the main quest where you get to control the draugr after that, returning to the cell "wyrmstooth barrow temple" (or reloading the save) the camera get stuck were the draugr died. I however fixed it i think by using "disable" then "enable" on the draugr after it get stuck. I don't know if the same can happens with some spells from apocalypse that also make you control other npc, and i'm not really sure how smoothcam works but maybe to alleviate the hassle of those bugs you can have an mcm option to reset smoothcam to the player position or something?

**Comment by mwilsnd** [comment] 2021-11-17 20:26
Fixed in 1.6

**Closed as completed by mwilsnd** 2021-11-17 20:26 UTC
Labels: bug
